zabbix_export:
  version: '7.4'
  template_groups:
    - uuid: ed8b8d16b49849a68710cebebabf9305
      name: Custom
    - uuid: 919a8a3de4a54c6ab44688fbb8f5f464
      name: 'Templates/Network devices'
  templates:
    - uuid: 224a28dbde6a461ca91b237b336b070b
      template: 'ICMP Ping'
      name: 'ICMP Ping'
      groups:
        - name: Custom
        - name: 'Templates/Network devices'
      items:
        - uuid: 15d6324f6ec844c195aef6577a14ba9c
          name: 'ICMP ping'
          type: SIMPLE
          key: icmpping
          valuemap:
            name: 'Service state'
          tags:
            - tag: component
              value: health
            - tag: component
              value: network
          triggers:
            - uuid: c24189f72b454c3da795f9b3746a0f92
              expression: 'max(/ICMP Ping/icmpping,#3)=0'
              name: 'Unavailable by ICMP ping'
              priority: HIGH
              description: 'Last three attempts returned timeout.  Please check device connectivity.'
              tags:
                - tag: scope
                  value: availability
        - uuid: ecc123fa780145fabd0e577297ae7f47
          name: 'ICMP loss'
          type: SIMPLE
          key: icmppingloss
          value_type: FLOAT
          units: '%'
          tags:
            - tag: component
              value: health
            - tag: component
              value: network
          triggers:
            - uuid: 7c25e080fdae408ea61f26361ac84761
              expression: 'min(/ICMP Ping/icmppingloss,5m)>{$ICMP_LOSS_WARN} and min(/ICMP Ping/icmppingloss,5m)<100'
              name: 'High ICMP ping loss'
              opdata: 'Loss: {ITEM.LASTVALUE1}'
              priority: WARNING
              dependencies:
                - name: 'Unavailable by ICMP ping'
                  expression: 'max(/ICMP Ping/icmpping,#3)=0'
              tags:
                - tag: scope
                  value: availability
                - tag: scope
                  value: performance
        - uuid: acfff0932f5d45b79653752fbdd1ee65
          name: 'ICMP response time'
          type: SIMPLE
          key: icmppingsec
          value_type: FLOAT
          units: s
          tags:
            - tag: component
              value: health
            - tag: component
              value: network
          triggers:
            - uuid: d61ac9eacd6246a39f7a6aeb74cbd81b
              expression: 'avg(/ICMP Ping/icmppingsec,5m)>{$ICMP_RESPONSE_TIME_WARN}'
              name: 'High ICMP ping response time'
              opdata: 'Value: {ITEM.LASTVALUE1}'
              priority: WARNING
              description: 'Average ICMP response time is too high.'
              dependencies:
                - name: 'High ICMP ping loss'
                  expression: 'min(/ICMP Ping/icmppingloss,5m)>{$ICMP_LOSS_WARN} and min(/ICMP Ping/icmppingloss,5m)<100'
                - name: 'Unavailable by ICMP ping'
                  expression: 'max(/ICMP Ping/icmpping,#3)=0'
              tags:
                - tag: scope
                  value: availability
                - tag: scope
                  value: performance
      tags:
        - tag: build
          value: custom
        - tag: class
          value: network
      macros:
        - macro: '{$ICMP_LOSS_WARN}'
          value: '20'
          description: 'Warning threshold of ICMP packet loss in %.'
        - macro: '{$ICMP_RESPONSE_TIME_WARN}'
          value: '0.15'
          description: 'Warning threshold of the average ICMP response time in seconds.'
      dashboards:
        - uuid: ed2d0afe7fe04c60a2ff76539b01f737
          name: Problems
          pages:
            - widgets:
                - type: problemsbysv
                  name: 'Current Problems by Severity'
                  width: '72'
                  fields:
                    - type: STRING
                      name: reference
                      value: NBVEC
                    - type: INTEGER
                      name: severities.0
                      value: '0'
                    - type: INTEGER
                      name: severities.1
                      value: '1'
                    - type: INTEGER
                      name: severities.2
                      value: '2'
                    - type: INTEGER
                      name: severities.3
                      value: '3'
                    - type: INTEGER
                      name: severities.4
                      value: '4'
                    - type: INTEGER
                      name: severities.5
                      value: '5'
                    - type: INTEGER
                      name: show_opdata
                      value: '2'
                    - type: INTEGER
                      name: show_suppressed
                      value: '1'
                - type: problems
                  name: 'Current and Historical Problems'
                  'y': '2'
                  width: '72'
                  height: '7'
                  fields:
                    - type: STRING
                      name: reference
                      value: XGLNS
                    - type: INTEGER
                      name: severities.0
                      value: '0'
                    - type: INTEGER
                      name: severities.1
                      value: '1'
                    - type: INTEGER
                      name: severities.2
                      value: '2'
                    - type: INTEGER
                      name: severities.3
                      value: '3'
                    - type: INTEGER
                      name: severities.4
                      value: '4'
                    - type: INTEGER
                      name: severities.5
                      value: '5'
                    - type: INTEGER
                      name: show
                      value: '2'
                    - type: INTEGER
                      name: show_lines
                      value: '50'
                    - type: INTEGER
                      name: show_opdata
                      value: '1'
                    - type: INTEGER
                      name: show_suppressed
                      value: '1'
                    - type: INTEGER
                      name: show_symptoms
                      value: '1'
                    - type: INTEGER
                      name: show_tags
                      value: '3'
        - uuid: 0196050e257c43789661e14c823b343c
          name: Summary
          pages:
            - widgets:
                - type: gauge
                  name: 'ICMP Response Time'
                  width: '15'
                  height: '3'
                  fields:
                    - type: ITEM
                      name: itemid.0
                      value:
                        host: 'ICMP Ping'
                        key: icmppingsec
                    - type: STRING
                      name: max
                      value: '60'
                    - type: STRING
                      name: min
                      value: '0'
                    - type: INTEGER
                      name: show.0
                      value: '2'
                    - type: INTEGER
                      name: show.1
                      value: '4'
                    - type: INTEGER
                      name: show.2
                      value: '5'
                    - type: STRING
                      name: thresholds.0.color
                      value: 3BC97D
                    - type: STRING
                      name: thresholds.0.threshold
                      value: '0'
                    - type: STRING
                      name: thresholds.1.color
                      value: FCCB1D
                    - type: STRING
                      name: thresholds.1.threshold
                      value: '15'
                    - type: STRING
                      name: thresholds.2.color
                      value: E65660
                    - type: STRING
                      name: thresholds.2.threshold
                      value: '20'
                    - type: INTEGER
                      name: th_show_arc
                      value: '1'
                    - type: INTEGER
                      name: th_show_labels
                      value: '1'
                - type: gauge
                  name: 'ICMP Loss'
                  'y': '3'
                  width: '15'
                  height: '3'
                  fields:
                    - type: ITEM
                      name: itemid.0
                      value:
                        host: 'ICMP Ping'
                        key: icmppingloss
                    - type: STRING
                      name: max
                      value: '60'
                    - type: STRING
                      name: min
                      value: '0'
                    - type: INTEGER
                      name: show.0
                      value: '2'
                    - type: INTEGER
                      name: show.1
                      value: '4'
                    - type: INTEGER
                      name: show.2
                      value: '5'
                    - type: STRING
                      name: thresholds.0.color
                      value: 3BC97D
                    - type: STRING
                      name: thresholds.0.threshold
                      value: '0'
                    - type: STRING
                      name: thresholds.1.color
                      value: FCCB1D
                    - type: STRING
                      name: thresholds.1.threshold
                      value: '15'
                    - type: STRING
                      name: thresholds.2.color
                      value: E65660
                    - type: STRING
                      name: thresholds.2.threshold
                      value: '20'
                    - type: INTEGER
                      name: th_show_arc
                      value: '1'
                    - type: INTEGER
                      name: th_show_labels
                      value: '1'
                - type: svggraph
                  name: 'ICMP Response Time'
                  x: '15'
                  width: '57'
                  height: '3'
                  fields:
                    - type: STRING
                      name: ds.0.color
                      value: 00BFFF
                    - type: STRING
                      name: ds.0.items.0
                      value: 'ICMP response time'
                    - type: STRING
                      name: reference
                      value: VHKRB
                    - type: INTEGER
                      name: righty
                      value: '0'
                - type: svggraph
                  name: 'ICMP Loss'
                  x: '15'
                  'y': '3'
                  width: '57'
                  height: '3'
                  fields:
                    - type: STRING
                      name: ds.0.color
                      value: FF465C
                    - type: STRING
                      name: ds.0.items.0
                      value: 'ICMP loss'
                    - type: STRING
                      name: reference
                      value: QQPIV
                    - type: INTEGER
                      name: righty
                      value: '0'
      valuemaps:
        - uuid: 0b4c1fca30174e7989e3659a16e98b02
          name: 'Service state'
          mappings:
            - value: '0'
              newvalue: Down
            - value: '1'
              newvalue: Up
        - uuid: 40e4a7bb897f4dacb5e8442bb67f08fc
          name: zabbix.host.available
          mappings:
            - value: '0'
              newvalue: 'not available'
            - value: '1'
              newvalue: available
            - value: '2'
              newvalue: unknown
