---
- name: Install required system packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - libpq-dev
      - libssl-dev
      - zlib1g-dev
      - git
      - python3-psycopg2
      - acl
      - qemu-guest-agent
    state: present
    update_cache: true
  tags:
    - common
