all:
  children:
    zabbix:
      children:
        zabbix_servers:
          hosts:
            node-1:
              ansible_host: 10.0.1.10
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              zabbix_server_dbhost: localhost
              zabbix_server_dbname: zabbix
              zabbix_server_dbuser: zabbix
              zabbix_server_dbpassword: 21hMBt8e
        zabbix_proxies:
          hosts:
            node-2:
              ansible_host: 10.0.1.10
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              zabbix_proxy_server: 192.168.10.10
              zabbix_proxy_dbhost: localhost
              zabbix_proxy_dbname: zabbix_proxy
              zabbix_proxy_dbuser: zabbix_proxy
              zabbix_proxy_dbpassword: PdXuybdA
            node-3:
              ansible_host: 10.0.1.10
              ansible_user: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
              zabbix_proxy_server: 192.168.10.10
              zabbix_proxy_dbhost: localhost
              zabbix_proxy_dbname: zabbix_proxy
              zabbix_proxy_dbuser: zabbix_proxy
              zabbix_proxy_dbpassword: xKWJaOMe
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
